name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: go install

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          gofmt: true
          gofmt_args: "-s -w -e -l ."
          golint: true
          golint_args: "./..."
